platform :ios, '13.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  # Flutter Pod
  use_frameworks!
  use_modular_headers!

  flutter_application_path = '../'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
end
