name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'
          channel: stable

      - name: Clean Flutter project
        run: flutter clean

      # ✅ This step generates .ios/Flutter/podhelper.rb
      - name: Generate iOS platform folders
        run: flutter create .

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod repo update

      # ✅ Extra safety: run a prebuild to make sure .ios exists
      - name: Pre-generate iOS build
        run: flutter build ios --no-codesign || true

      # ✅ Debug: check that podhelper.rb now exists
      - name: List Flutter helper
        run: ls -R .ios || true

      - name: Run pod install
        working-directory: ios
        run: pod install --verbose

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Create Payload folder
        working-directory: build/ios/iphoneos
        run: mkdir Payload && mv Runner.app Payload/

      - name: Zip IPA
        working-directory: build/ios/iphoneos
        run: zip -qq -r -9 FlutterApp.ipa Payload

      - name: Upload IPA to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterApp.ipa
          tag: v1.0.0
          overwrite: true
          body: "First iOS release built by GitHub Actions"
