name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'   # Match your local Flutter version
          channel: stable

      # 3️⃣ Clean project
      - name: Clean Flutter project
        run: flutter clean

      # 4️⃣ Generate iOS platform folders (creates .ios/Flutter/podhelper.rb)
      - name: Generate iOS platform folders
        run: flutter create .

      # 5️⃣ Install Flutter dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # 6️⃣ Install CocoaPods (ensures latest version)
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod repo update

      # 7️⃣ Pre-generate iOS build to ensure .ios folder exists
      - name: Pre-generate iOS build
        run: flutter build ios --no-codesign || true

      # 8️⃣ Debug: list files to confirm .ios was generated
      - name: Debug list files
        run: ls -la && ls -la .ios && ls -la .ios/Flutter || true

      # 9️⃣ Run pod install explicitly
      - name: Run pod install
        working-directory: ios
        run: pod install --verbose

      # 🔟 Build iOS (no codesign)
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      # 1️⃣1️⃣ Package .ipa
      - name: Create Payload folder
        working-directory: build/ios/iphoneos
        run: mkdir Payload && mv Runner.app Payload/

      - name: Zip IPA
        working-directory: build/ios/iphoneos
        run: zip -qq -r -9 FlutterApp.ipa Payload

      # 1️⃣2️⃣ Upload IPA to GitHub Release
      - name: Upload IPA to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterApp.ipa
          tag: v1.0.0
          overwrite: true
          body: "First iOS release built by GitHub Actions"
