name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Flutter environment
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'
          channel: stable

      # 3️⃣ Install CocoaPods gem (latest stable)
      - name: Setup CocoaPods
        run: |
          sudo gem install cocoapods -v 1.16.2
          pod --version

      # 4️⃣ Clean Flutter project
      - name: Clean Flutter project
        run: flutter clean

      # 5️⃣ Get Flutter dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # 6️⃣ Precache iOS artifacts
      - name: Flutter precache iOS
        run: flutter precache --ios

      # 7️⃣ Clean CocoaPods artifacts & repos
      - name: CocoaPods cleanup
        run: |
          cd ios
          pod deintegrate || true
          pod cache clean --all
          pod repo update
          rm -rf Pods Podfile.lock

      # 8️⃣ Install CocoaPods dependencies
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install --verbose

      # 9️⃣ Build iOS app (release, no codesign)
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      # 🔟 Package IPA
      - name: Package IPA
        working-directory: build/ios/iphoneos
        run: |
          mkdir -p Payload
          mv Runner.app Payload/
          zip -qr FlutterApp.ipa Payload

      # 1️⃣1️⃣ Upload IPA artifact
      - name: Upload IPA as release artifact
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterApp.ipa
          tag: v1.0.0
          overwrite: true
          body: "First iOS release built by GitHub Actions"
