name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 📦 Build iOS IPA
    runs-on: macos-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Flutter (ensure correct Flutter version with Dart 3.8.1)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'
          channel: stable

      # 3️⃣ Clean Flutter project (optional but recommended)
      - name: Clean Flutter project
        run: flutter clean

      # 4️⃣ Install Flutter dependencies and generate iOS tooling files
      - name: Prepare iOS build folder
        run: flutter pub get && flutter precache ios

      # 5️⃣ Build iOS without codesign
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      # 6️⃣ Package .ipa
      - name: Create Payload folder
        working-directory: build/ios/iphoneos
        run: mkdir Payload && mv Runner.app Payload/

      - name: Zip IPA
        working-directory: build/ios/iphoneos
        run: zip -qq -r -9 FlutterApp.ipa Payload

      # 7️⃣ Upload IPA as a release artifact
      - name: Upload IPA to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterApp.ipa
          tag: v1.0.0
          overwrite: true
          body: "First iOS release built by GitHub Actions"
