name: iOS IPA Build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3' # or your Flutter version
          channel: stable

      # 3️⃣ Setup Ruby & CocoaPods
      - name: Setup CocoaPods
        run: |
          sudo gem install cocoapods -v 1.15.2
          pod --version

      # 4️⃣ Clean Flutter build
      - name: Flutter clean
        run: flutter clean

      # 5️⃣ Install Flutter dependencies
      - name: Flutter pub get
        run: flutter pub get

      # 6️⃣ Precache iOS artifacts
      - name: Flutter precache for iOS
        run: flutter precache --ios

      # 7️⃣ Clean and reinstall CocoaPods
      - name: CocoaPods reset & install
        run: |
          cd ios
          pod deintegrate || true
          pod repo update
          pod install --verbose

      # 8️⃣ Build iOS (Release, no codesign)
      - name: Flutter build iOS
        run: flutter build ios --release --no-codesign

      # 9️⃣ Package IPA
      - name: Package IPA
        working-directory: build/ios/iphoneos
        run: |
          mkdir -p Payload
          mv Runner.app Payload/
          zip -qr FlutterApp.ipa Payload

      # 🔟 Upload IPA artifact to workflow
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: FlutterApp.ipa
          path: build/ios/iphoneos/FlutterApp.ipa
