name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-13   # ✅ Use macOS 13 to get Xcode 15.4 (Swift 5.10)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'
          channel: stable

      # ✅ Force Xcode 15.4 (Swift 5.10)
      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Flutter clean
        run: flutter clean

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Precache iOS
        run: flutter precache --ios

      - name: Install CocoaPods
        working-directory: ios
        run: |
          pod repo update
          pod deintegrate
          pod install --repo-update

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Create Payload folder
        working-directory: build/ios/iphoneos
        run: mkdir Payload && mv Runner.app Payload/

      - name: Zip IPA
        working-directory: build/ios/iphoneos
        run: zip -qq -r -9 FlutterApp.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: FlutterApp
          path: build/ios/iphoneos/FlutterApp.ipa
