name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14
    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'
          channel: stable

      # 🔥 3️⃣ Force Xcode 15.4 (fixes Firebase Swift errors)
      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      # 4️⃣ Clean and fetch dependencies
      - name: Flutter clean
        run: flutter clean

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Precache iOS
        run: flutter precache --ios

      # 5️⃣ Clean and install CocoaPods
      - name: Install CocoaPods
        working-directory: ios
        run: |
          pod repo update
          pod deintegrate
          pod install --repo-update

      # 6️⃣ Build iOS without codesigning
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      # 7️⃣ Package IPA
      - name: Create Payload folder
        working-directory: build/ios/iphoneos
        run: mkdir Payload && mv Runner.app Payload/

      - name: Zip IPA
        working-directory: build/ios/iphoneos
        run: zip -qq -r -9 FlutterApp.ipa Payload

      # 8️⃣ Upload IPA as artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: FlutterApp
          path: build/ios/iphoneos/FlutterApp.ipa
